from functools import lru_cache

from flowfile_core.schemas.schemas import NodeDefault, NodeTag, NodeTemplate


def get_all_standard_nodes() -> tuple[list[NodeTemplate], dict[str, NodeTemplate], dict[str, NodeDefault]]:
    """
    Initializes and returns the complete list, dict, and defaults for all nodes.
    """
    nodes_list: list[NodeTemplate] = [
        NodeTemplate(
            name="External source",
            item="external_source",
            input=0,
            output=1,
            image="external_source.svg",
            node_type="input",
            transform_type="other",
            node_group="input",
            prod_ready=False,
            drawer_title="External Source",
            drawer_intro="Connect to external data sources and APIs",
            laziness="eager",
            tags=[NodeTag.API, NodeTag.REST, NodeTag.HTTP, NodeTag.EXTERNAL],
        ),
        NodeTemplate(
            name="Manual input",
            item="manual_input",
            input=0,
            output=1,
            transform_type="other",
            node_type="input",
            image="manual_input.svg",
            node_group="input",
            drawer_title="Manual Input",
            drawer_intro="Create data directly",
            laziness="lazy",
            tags=[NodeTag.MANUAL, NodeTag.PASTE, NodeTag.INPUT],
        ),
        NodeTemplate(
            name="Read data",
            item="read",
            input=0,
            output=1,
            transform_type="other",
            node_type="input",
            image="input_data.svg",
            node_group="input",
            drawer_title="Read Data",
            drawer_intro="Load data from CSV, Excel, or Parquet files",
            # TODO: resolve laziness in check_upstream_laziness via isinstance check (like catalog_reader),
            # then change to "lazy"
            laziness="conditional",
            tags=[
                NodeTag.CSV,
                NodeTag.EXCEL,
                NodeTag.PARQUET,
                NodeTag.JSON,
                NodeTag.FILE,
                NodeTag.IMPORT,
                NodeTag.READ,
            ],
        ),
        NodeTemplate(
            name="Join",
            item="join",
            input=2,
            output=1,
            transform_type="wide",
            node_type="process",
            image="join.svg",
            node_group="combine",
            drawer_title="Join Datasets",
            drawer_intro="Merge two datasets based on matching column values",
            laziness="lazy",
            tags=[NodeTag.JOIN, NodeTag.MERGE, NodeTag.LOOKUP, NodeTag.VLOOKUP, NodeTag.INNER, NodeTag.OUTER],
        ),
        NodeTemplate(
            name="Formula",
            item="formula",
            input=1,
            output=1,
            transform_type="narrow",
            node_type="process",
            image="formula.svg",
            node_group="transform",
            drawer_title="Formula Editor",
            drawer_intro="Create or modify columns using custom expressions",
            laziness="lazy",
            tags=[NodeTag.FORMULA, NodeTag.EXPRESSION, NodeTag.TRANSFORM,
                  NodeTag.CALCULATE, NodeTag.MATH, NodeTag.CONCAT, NodeTag.SUM],
        ),
        NodeTemplate(
            name="Write data",
            item="output",
            input=1,
            output=0,
            transform_type="other",
            image="output.svg",
            node_type="output",
            node_group="output",
            drawer_title="Write Data",
            drawer_intro="Save your data as CSV, Excel, or Parquet files",
            laziness="eager",
            tags=[
                NodeTag.CSV,
                NodeTag.EXCEL,
                NodeTag.PARQUET,
                NodeTag.JSON,
                NodeTag.FILE,
                NodeTag.EXPORT,
                NodeTag.SAVE,
                NodeTag.WRITE,
            ],
        ),
        NodeTemplate(
            name="API response",
            item="api_response",
            input=1,
            output=0,
            transform_type="other",
            image="api_response.svg",
            node_type="output",
            node_group="output",
            drawer_title="API Response",
            drawer_intro="Return this dataset as the body of an HTTP API endpoint",
            laziness="eager",
            tags=[NodeTag.API, NodeTag.REST, NodeTag.HTTP, NodeTag.RESPONSE],
        ),
        NodeTemplate(
            name="Select data",
            item="select",
            input=1,
            output=1,
            transform_type="narrow",
            node_type="process",
            image="select.svg",
            node_group="transform",
            drawer_title="Select Columns",
            drawer_intro="Choose, rename, and reorder columns to keep",
            laziness="lazy",
            tags=[NodeTag.SELECT, NodeTag.COLUMNS, NodeTag.RENAME, NodeTag.REORDER, NodeTag.PROJECTION],
        ),
        NodeTemplate(
            name="Rename columns",
            item="dynamic_rename",
            input=1,
            output=1,
            transform_type="narrow",
            node_type="process",
            image="dynamic_rename.svg",
            node_group="transform",
            drawer_title="Rename Columns",
            drawer_intro="Bulk-rename columns by prefix, suffix, or a formula",
            laziness="lazy",
            tags=[NodeTag.RENAME, NodeTag.COLUMNS],
        ),
        NodeTemplate(
            name="Filter data",
            item="filter",
            input=1,
            output=1,
            transform_type="narrow",
            node_type="process",
            image="filter.svg",
            node_group="transform",
            drawer_title="Filter Rows",
            drawer_intro="Keep only rows that match your conditions",
            laziness="lazy",
            tags=[NodeTag.FILTER, NodeTag.WHERE, NodeTag.SUBSET],
        ),
        NodeTemplate(
            name="Group by",
            item="group_by",
            input=1,
            output=1,
            transform_type="wide",
            node_type="process",
            image="group_by.svg",
            node_group="aggregate",
            drawer_title="Group By",
            drawer_intro="Aggregate data by grouping and calculating statistics",
            laziness="lazy",
            tags=[
                NodeTag.GROUP_BY,
                NodeTag.AGGREGATE,
                NodeTag.SUM,
                NodeTag.MEAN,
                NodeTag.AVERAGE,
                NodeTag.COUNT,
                NodeTag.MIN,
                NodeTag.MAX,
                NodeTag.MEDIAN,
                NodeTag.SUMMARIZE,
            ],
        ),
        NodeTemplate(
            name="Window functions",
            item="window_functions",
            input=1,
            output=1,
            transform_type="wide",
            node_type="process",
            image="window_functions.svg",
            node_group="aggregate",
            drawer_title="Window Functions",
            drawer_intro="Rolling, cumulative, rank and tile calculations (optionally per partition)",
            laziness="lazy",
            tags=[
                NodeTag.WINDOW,
                NodeTag.ROLLING,
                NodeTag.CUMULATIVE,
                NodeTag.RANK,
                NodeTag.PARTITION,
                NodeTag.LAG,
                NodeTag.LEAD,
            ],
        ),
        NodeTemplate(
            name="Fuzzy match",
            item="fuzzy_match",
            input=2,
            output=1,
            transform_type="wide",
            image="fuzzy_match.svg",
            node_type="process",
            node_group="combine",
            drawer_title="Fuzzy Match",
            drawer_intro="Join datasets based on similar values instead of exact matches",
            laziness="eager",
            tags=[NodeTag.FUZZY, NodeTag.SIMILARITY, NodeTag.LEVENSHTEIN, NodeTag.JOIN, NodeTag.LOOKUP],
        ),
        NodeTemplate(
            name="Sort data",
            item="sort",
            input=1,
            output=1,
            transform_type="wide",
            node_type="process",
            image="sort.svg",
            node_group="transform",
            drawer_title="Sort Data",
            drawer_intro="Order your data by one or more columns",
            laziness="lazy",
            tags=[NodeTag.SORT, NodeTag.ORDER, NodeTag.RANK, NodeTag.ASCENDING, NodeTag.DESCENDING],
        ),
        NodeTemplate(
            name="Add record Id",
            item="record_id",
            input=1,
            output=1,
            transform_type="wide",
            node_type="process",
            image="record_id.svg",
            node_group="transform",
            drawer_title="Add Record ID",
            drawer_intro="Generate unique identifiers for each row",
            laziness="lazy",
            tags=[NodeTag.RECORD_ID, NodeTag.ROW_NUMBER, NodeTag.INDEX],
        ),
        NodeTemplate(
            name="Take Sample",
            item="sample",
            input=1,
            output=1,
            transform_type="narrow",
            node_type="process",
            image="sample.svg",
            node_group="transform",
            drawer_title="Take Sample",
            drawer_intro="Work with a subset of your data",
            laziness="lazy",
            tags=[NodeTag.SAMPLE, NodeTag.SUBSET, NodeTag.LIMIT, NodeTag.HEAD],
        ),
        NodeTemplate(
            name="Random Split",
            item="random_split",
            input=1,
            output=2,
            output_names=["train", "test"],
            transform_type="narrow",
            node_type="process",
            image="random_split.svg",
            node_group="ml",
            drawer_title="Random Split",
            drawer_intro="Randomly partition rows into named groups (e.g. train/test)",
            laziness="lazy",
            tags=[NodeTag.SPLIT, NodeTag.TRAIN, NodeTag.TEST, NodeTag.ML, NodeTag.PARTITION],
        ),
        NodeTemplate(
            name="Explore data",
            item="explore_data",
            input=1,
            output=0,
            transform_type="other",
            node_type="output",
            image="explore_data.svg",
            node_group="output",
            drawer_title="Explore Data",
            drawer_intro="Interactive data exploration and analysis",
            laziness="eager",
            tags=[NodeTag.EXPLORE, NodeTag.PROFILE, NodeTag.PREVIEW, NodeTag.EDA, NodeTag.STATISTICS, NodeTag.VISUALIZE,
                  NodeTag.INSIGHT, NodeTag.BAR_CHART, NodeTag.GRAPHS],
        ),
        NodeTemplate(
            name="Pivot data",
            item="pivot",
            input=1,
            output=1,
            transform_type="wide",
            image="pivot.svg",
            node_type="process",
            node_group="aggregate",
            drawer_title="Pivot Data",
            drawer_intro="Convert data from long format to wide format",
            laziness="eager",
            tags=[NodeTag.PIVOT, NodeTag.CROSSTAB, NodeTag.RESHAPE],
        ),
        NodeTemplate(
            name="Unpivot data",
            item="unpivot",
            input=1,
            output=1,
            transform_type="wide",
            node_type="process",
            image="unpivot.svg",
            node_group="aggregate",
            drawer_title="Unpivot Data",
            drawer_intro="Transform data from wide format to long format",
            laziness="lazy",
            tags=[NodeTag.UNPIVOT, NodeTag.MELT, NodeTag.RESHAPE],
        ),
        NodeTemplate(
            name="Union data",
            item="union",
            input=10,
            output=1,
            transform_type="narrow",
            node_type="process",
            image="union.svg",
            multi=True,
            node_group="combine",
            drawer_title="Union Data",
            drawer_intro="Stack multiple datasets by combining rows",
            laziness="lazy",
            tags=[NodeTag.UNION, NodeTag.CONCAT, NodeTag.APPEND],
        ),
        NodeTemplate(
            name="Drop duplicates",
            item="unique",
            input=1,
            output=1,
            transform_type="wide",
            node_type="process",
            image="unique.svg",
            node_group="transform",
            drawer_title="Drop Duplicates",
            drawer_intro="Remove duplicate rows based on selected columns",
            laziness="lazy",
            tags=[NodeTag.UNIQUE, NodeTag.DEDUPE, NodeTag.DISTINCT, NodeTag.DROP_DUPLICATES],
        ),
        NodeTemplate(
            name="Graph solver",
            item="graph_solver",
            input=1,
            output=1,
            transform_type="other",
            node_type="process",
            image="graph_solver.svg",
            node_group="combine",
            drawer_title="Graph Solver",
            drawer_intro="Group related records in graph-structured data",
            laziness="lazy",
            tags=[NodeTag.GRAPH, NodeTag.NETWORK, NodeTag.CLUSTER, NodeTag.CONNECTED_COMPONENTS],
        ),
        NodeTemplate(
            name="Count records",
            item="record_count",
            input=1,
            output=1,
            transform_type="wide",
            node_type="process",
            image="record_count.svg",
            node_group="aggregate",
            drawer_title="Count Records",
            drawer_intro="Calculate the total number of rows",
            laziness="lazy",
            tags=[NodeTag.RECORD_COUNT, NodeTag.COUNT, NodeTag.ROWS],
        ),
        NodeTemplate(
            name="Cross join",
            item="cross_join",
            input=2,
            output=1,
            transform_type="wide",
            node_type="process",
            image="cross_join.svg",
            node_group="combine",
            drawer_title="Cross Join",
            drawer_intro="Create all possible combinations between two datasets",
            laziness="lazy",
            tags=[NodeTag.CROSS_JOIN, NodeTag.CARTESIAN, NodeTag.JOIN],
        ),
        NodeTemplate(
            name="Text to rows",
            item="text_to_rows",
            input=1,
            output=1,
            transform_type="wide",
            node_type="process",
            image="text_to_rows.svg",
            node_group="transform",
            drawer_title="Text to Rows",
            drawer_intro="Split text into multiple rows based on a delimiter",
            laziness="lazy",
            tags=[NodeTag.TEXT_TO_ROWS, NodeTag.SPLIT, NodeTag.EXPLODE],
        ),
        NodeTemplate(
            name="Polars code",
            item="polars_code",
            input=10,
            output=1,
            transform_type="narrow",
            image="polars_code.svg",
            node_group="transform",
            node_type="process",
            multi=True,
            can_be_start=True,
            drawer_title="Polars Code",
            drawer_intro="Write custom Polars DataFrame transformations",
            # TODO: resolve laziness in check_upstream_laziness via isinstance check (like catalog_reader),
            # then change to "lazy"
            laziness="conditional",
            tags=[NodeTag.POLARS, NodeTag.CODE, NodeTag.PYTHON, NodeTag.SCRIPT, NodeTag.CUSTOM, NodeTag.DATAFRAME,
                  NodeTag.TRANSFORM],
        ),
        NodeTemplate(
            name="SQL Query",
            item="sql_query",
            input=10,
            output=1,
            transform_type="narrow",
            image="sql_query.svg",
            node_group="transform",
            node_type="process",
            multi=True,
            can_be_start=True,
            drawer_title="SQL Query",
            drawer_intro="Write SQL queries against connected data sources",
            laziness="lazy",
            tags=[NodeTag.SQL, NodeTag.QUERY, NodeTag.DUCKDB],
        ),
        NodeTemplate(
            name="Python Script",
            item="python_script",
            input=10,
            output=1,
            transform_type="narrow",
            image="python_code.svg",
            node_group="transform",
            multi=True,
            can_be_start=True,
            node_type="process",
            drawer_title="Python Script",
            drawer_intro="Execute Python code on an isolated kernel container",
            laziness="eager",
            tags=[NodeTag.PYTHON, NodeTag.CODE, NodeTag.SCRIPT, NodeTag.KERNEL, NodeTag.CUSTOM, NodeTag.TRANSFORM],
        ),
        NodeTemplate(
            name="Read from Database",
            item="database_reader",
            input=0,
            output=1,
            node_type="input",
            transform_type="other",
            image="database_reader.svg",
            node_group="input",
            drawer_title="Database Reader",
            drawer_intro="Load data from database tables or queries",
            laziness="eager",
            tags=[
                NodeTag.DATABASE,
                NodeTag.SQL,
                NodeTag.POSTGRES,
                NodeTag.MYSQL,
                NodeTag.SQL_SERVER,
                NodeTag.SNOWFLAKE,
                NodeTag.ORACLE,
                NodeTag.SQLITE,
                NodeTag.REDSHIFT,
                NodeTag.BIGQUERY,
                NodeTag.QUERY,
                NodeTag.TABLE,
            ],
        ),
        NodeTemplate(
            name="Write to Database",
            item="database_writer",
            input=1,
            output=0,
            transform_type="other",
            node_type="output",
            image="database_writer.svg",
            node_group="output",
            drawer_title="Database Writer",
            drawer_intro="Save data to database tables",
            laziness="eager",
            tags=[
                NodeTag.DATABASE,
                NodeTag.SQL,
                NodeTag.POSTGRES,
                NodeTag.MYSQL,
                NodeTag.SNOWFLAKE,
                NodeTag.REDSHIFT,
                NodeTag.BIGQUERY,
                NodeTag.TABLE,
            ],
        ),
        NodeTemplate(
            name="Read from cloud provider",
            item="cloud_storage_reader",
            input=0,
            output=1,
            transform_type="other",
            node_type="input",
            image="cloud_storage_reader.svg",
            node_group="input",
            drawer_title="Cloud Storage Reader",
            drawer_intro="Read data from AWS S3 and other cloud storage",
            # TODO: resolve laziness in check_upstream_laziness via isinstance check (like catalog_reader),
            # then change to "lazy"
            laziness="conditional",
            tags=[
                NodeTag.S3,
                NodeTag.AWS,
                NodeTag.AZURE,
                NodeTag.ADLS,
                NodeTag.GCS,
                NodeTag.BLOB,
                NodeTag.BUCKET,
                NodeTag.CLOUD,
                NodeTag.DELTA,
            ],
        ),
        NodeTemplate(
            name="Read from Catalog",
            item="catalog_reader",
            input=0,
            output=1,
            transform_type="other",
            node_type="input",
            image="catalog_reader.svg",
            node_group="input",
            drawer_title="Catalog Reader",
            drawer_intro="Read a table from the data catalog",
            laziness="lazy",
            tags=[NodeTag.CATALOG, NodeTag.DELTA, NodeTag.TABLE, NodeTag.LAKEHOUSE, NodeTag.TIME_TRAVEL],
        ),
        NodeTemplate(
            name="Write to Catalog",
            item="catalog_writer",
            input=1,
            output=0,
            transform_type="other",
            node_type="output",
            image="catalog_writer.svg",
            node_group="output",
            drawer_title="Catalog Writer",
            drawer_intro="Save data as a table in the data catalog",
            laziness="eager",
            tags=[NodeTag.CATALOG, NodeTag.DELTA, NodeTag.TABLE, NodeTag.LAKEHOUSE],
        ),
        NodeTemplate(
            name="Write to cloud provider",
            item="cloud_storage_writer",
            input=1,
            output=0,
            transform_type="other",
            node_type="output",
            image="cloud_storage_writer.svg",
            node_group="output",
            drawer_title="Cloud Storage Writer",
            drawer_intro="Save data to AWS S3 and other cloud storage",
            laziness="eager",
            tags=[
                NodeTag.S3,
                NodeTag.AWS,
                NodeTag.AZURE,
                NodeTag.ADLS,
                NodeTag.GCS,
                NodeTag.BLOB,
                NodeTag.BUCKET,
                NodeTag.CLOUD,
                NodeTag.DELTA,
            ],
        ),
        NodeTemplate(
            name="Kafka Source",
            item="kafka_source",
            input=0,
            output=1,
            node_type="input",
            transform_type="other",
            image="kafka_source.svg",
            node_group="input",
            drawer_title="Kafka Source",
            drawer_intro="Read data from a Kafka or Redpanda topic",
            laziness="eager",
            tags=[NodeTag.KAFKA, NodeTag.REDPANDA, NodeTag.STREAMING, NodeTag.TOPIC],
        ),
        NodeTemplate(
            name="Google Analytics",
            item="google_analytics_reader",
            input=0,
            output=1,
            node_type="input",
            transform_type="other",
            image="google_analytics.svg",
            node_group="input",
            drawer_title="Google Analytics",
            drawer_intro="Load reports from a Google Analytics 4 property",
            laziness="eager",
            tags=[NodeTag.GOOGLE_ANALYTICS, NodeTag.GA4, NodeTag.ANALYTICS],
        ),
        NodeTemplate(
            name="REST API",
            item="rest_api_reader",
            input=0,
            output=1,
            node_type="input",
            transform_type="other",
            image="rest_api_reader.svg",
            node_group="input",
            drawer_title="REST API",
            drawer_intro="Read JSON data from a REST API with auth and pagination",
            laziness="eager",
            tags=[NodeTag.REST, NodeTag.API, NodeTag.HTTP, NodeTag.JSON, NodeTag.PAGINATION],
        ),
        NodeTemplate(
            name="Train Model",
            item="train_model",
            input=1,
            output=1,
            transform_type="other",
            node_type="process",
            image="train_model.svg",
            node_group="ml",
            drawer_title="Train ML Model",
            drawer_intro="Fit a regression or classification model; optionally save it to the catalog",
            laziness="eager",
            tags=[
                NodeTag.ML,
                NodeTag.MACHINE_LEARNING,
                NodeTag.TRAIN,
                NodeTag.MODEL,
                NodeTag.REGRESSION,
                NodeTag.CLASSIFICATION,
            ],
        ),
        NodeTemplate(
            name="Apply Model",
            item="apply_model",
            input=1,
            output=1,
            transform_type="wide",
            node_type="process",
            image="apply_model.svg",
            node_group="ml",
            drawer_title="Apply ML Model",
            drawer_intro="Score data with an upstream Train Model node, or with a trained model from the catalog",
            laziness="eager",
            tags=[NodeTag.ML, NodeTag.MACHINE_LEARNING, NodeTag.PREDICT, NodeTag.SCORE, NodeTag.MODEL],
        ),
        NodeTemplate(
            name="Evaluate Model",
            item="evaluate_model",
            input=1,
            output=1,
            transform_type="narrow",
            node_type="process",
            image="evaluate_model.svg",
            node_group="ml",
            drawer_title="Evaluate Model",
            drawer_intro="Compare actual vs predicted columns and compute quality metrics",
            laziness="eager",
            tags=[NodeTag.ML, NodeTag.MACHINE_LEARNING, NodeTag.EVALUATE, NodeTag.METRICS, NodeTag.MODEL],
        ),
        NodeTemplate(
            name="Wait For",
            item="wait_for",
            input=2,
            output=1,
            transform_type="other",
            node_type="process",
            image="wait_for.svg",
            node_group="combine",
            drawer_title="Wait For",
            drawer_intro="Pass the left input through; the right input only enforces ordering",
            laziness="eager",
            tags=[NodeTag.WAIT, NodeTag.DEPENDENCY],
        ),
        NodeTemplate(
            name="Spatial Read",
            item="spatial_read",
            input=0,
            output=1,
            node_group="input",
            image="input_data.svg",
            node_type="input",
            transform_type="other",
            laziness="eager",
            drawer_title="Spatial Reader",
            drawer_intro="Read geospatial data from Shapefiles, GeoParquet, or GeoJSON",
            tags=[
                NodeTag.SHAPEFILE,
                NodeTag.GEOJSON,
                NodeTag.GEOPARQUET,
                NodeTag.SPATIAL,
                NodeTag.GIS,
                NodeTag.GEOMETRY,
                NodeTag.READ,
                NodeTag.FILE,
                NodeTag.MAP,
            ],
        ),
        NodeTemplate(
            name="Spatial Join",
            item="spatial_join",
            input=2,
            output=1,
            node_group="combine",
            image="join.svg",
            node_type="process",
            transform_type="wide",
            laziness="eager",
            drawer_title="Spatial Join",
            drawer_intro="Join two datasets based on spatial predicates (intersects, contains, within)",
            tags=[
                NodeTag.SPATIAL,
                NodeTag.JOIN,
                NodeTag.GIS,
                NodeTag.GEOMETRY,
                NodeTag.INTERSECTS,
                NodeTag.CONTAINS,
                NodeTag.WITHIN,
                NodeTag.MAP,
            ],
        ),
        NodeTemplate(
            name="Buffer Geometry",
            item="buffer_geometry",
            input=1,
            output=1,
            node_group="transform",
            image="formula.svg",
            node_type="process",
            transform_type="narrow",
            laziness="eager",
            drawer_title="Buffer Geometry",
            drawer_intro="Generate distance buffers around geometries",
            tags=[
                NodeTag.SPATIAL,
                NodeTag.BUFFER,
                NodeTag.GIS,
                NodeTag.GEOMETRY,
                NodeTag.MAP,
            ],
        ),
    ]
    nodes_list.sort(key=lambda x: x.name)
    nodes_with_defaults = {"sample", "sort", "union", "select", "record_count"}

    def check_if_has_default_setting(node_item: str):
        return node_item in nodes_with_defaults

    node_defaults = {
        node.item: NodeDefault(
            node_name=node.name,
            node_type=node.node_type,
            transform_type=node.transform_type,
            has_default_settings=check_if_has_default_setting(node.item),
        )
        for node in nodes_list
    }
    node_dict = {n.item: n for n in nodes_list}

    node_dict["polars_lazy_frame"] = NodeTemplate(
        name="LazyFrame node",
        item="polars_lazy_frame",
        input=0,
        output=1,
        node_group="special",
        image="",
        node_type="input",
        transform_type="other",
        laziness="lazy",
    )

    return nodes_list, node_dict, node_defaults


@lru_cache(maxsize=1)
def get_source_node_types() -> tuple[str, ...]:
    """Source-only node types (no input port), compiled once at startup from the
    registry. Single source of truth for the connection validator and AI prose;
    excludes the dict-only ``polars_lazy_frame``.
    """
    templates, _, _ = get_all_standard_nodes()
    return tuple(sorted(t.item for t in templates if t.input == 0))


@lru_cache(maxsize=1)
def get_source_node_types_str() -> str:
    """Comma-joined source node types for prose mentions (single build site)."""
    return ", ".join(get_source_node_types())
